name: beefbox
favicon: null
layout_spectrum: 0.994102050550282
typography_spectrum: 0.25061
title: Beefbox
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6c2ebe'
    - '#ff0000'
    - '#bc1555'
    - '#8d2392'
    - '#de0c34'
  brandStrength: 0.875
  lightness: 0.4375
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
